/**
 * \file nepe2/mapper.h
 *
 * \brief The mapper interface maps a raw passphrase buffer into a password by
 * mapping the raw bits of this buffer into glyphs for the password.
 *
 * Example implementations might be a hex mapper, a Base64 encoder, or a raw
 * translation buffer of one to seven bit values (2 to 128 unique glyphs).
 *
 * \copyright 2026 Justin Handville.  Please see License.txt in this
 * distribution for the license terms under which this software is distributed.
 */

#pragma once

#include <nepe2/macro_tricks.h>
#include <nepe2/metadata.h>
#include <nepe2/secure_buffer.h>
#include <rcpr/allocator.h>
#include <rcpr/resource.h>

/* C++ compatibility. */
# ifdef   __cplusplus
extern "C" {
# endif /*__cplusplus*/

/**
 * \brief The mapper is an interface for mapping raw passphrase data into
 * password glyphs.
 */
typedef struct mapper mapper;

/**
 * \brief The MAPPER_REGISTER macro is a dummy annotation used by the build
 * script to automatically register a mapper implementation.
 */
#define MAPPER_REGISTER(x, y) REQUIRE_SEMICOLON_HERE

/**
 * \brief A mapper function takes an allocator and a raw generated password to
 * produce a secure buffer containing a password that has been mapped to a given
 * translation set or encoding.
 *
 * \param mapped        Pointer to the secure buffer pointer to be set to the
 *                      mapped password on success.
 * \param alloc         The allocator to use for this operation.
 * \param raw           The raw password to use for this operation.
 *
 * \returns a status code indicating success or failure.
 *      - STATUS_SUCCESS on success.
 *      - a non-zero error code on failure.
 */
typedef status (*mapper_fn)(
    secure_buffer** mapped, RCPR_SYM(allocator)* alloc,
    const secure_buffer* raw);

/**
 * \brief The mappers_register function is generated by the build script,
 * and registers all mapper implementations with the mapper registry.
 *
 * \returns a status code indicating success or failure.
 *      - STATUS_SUCCESS on success.
 *      - a non-zero error code on failure.
 */
status FN_DECL_MUST_CHECK mappers_register();

/******************************************************************************/
/* Start of constructors.                                                     */
/******************************************************************************/

/**
 * \brief Create a mapper instance with the given name and mapping function.
 *
 * \param m             Pointer to the mapper pointer to be set to the
 *                      created mapper instance on success.
 * \param alloc         The allocator to use for this operation.
 * \param name          The name of this mapper.
 * \param map_fn        The mapper function to use for this instance.
 *
 * \note This mapper instance is a \ref resource that must be released by
 * calling \ref resource_release on its resource handle when it is no longer
 * needed by the caller. The resource handle can be accessed by calling \ref
 * mapper_resource_handle on this mapper instance.
 *
 * \returns a status code indicating success or failure.
 *      - STATUS_SUCCESS on success.
 *      - a non-zero error code on failure.
 *
 * \pre
 *      - \p m must not reference a valid \ref mapper instance and
 *        must not be NULL.
 *      - \p alloc must reference a valid \ref allocator and must not be NULL.
 *      - \p name must be a valid string and must not be NULL.
 *      - \p map_fn must be a valid function and must not be NULL.
 * \post
 *      - On success, \p m is set to a pointer to a valid \ref mapper instance,
 *        which is a \ref resource owned by the caller that must be released
 *        when no longer needed.
 *      - On failure, \p m is set to NULL and an error status is returned.
 */
status FN_DECL_MUST_CHECK
mapper_create(
    mapper** m, RCPR_SYM(allocator)* alloc, const char* name, mapper_fn map_fn);

/******************************************************************************/
/* Start of accessors.                                                        */
/******************************************************************************/

/**
 * \brief Given a \ref mapper instance, return the resource handle for this
 * \ref mapper instance.
 *
 * \param m             The \ref mapper instance from which the resource handle
 *                      is returned.
 *
 * \returns the resource handle for this \ref mapper instance.
 */
RCPR_SYM(resource)*
mapper_resource_handle(mapper* m);

/**
 * \brief Register a mapper with the registry.
 *
 * \note The registry takes ownership of this mapper instance on success.
 *
 * \param m             The \ref mapper instance to register.
 *
 * \returns a status code indicating success or failure.
 *      - STATUS_SUCCESS on success.
 *      - a non-zero error code on failure.
 */
status FN_DECL_MUST_CHECK
mapper_registry_register(mapper* m);

/* C++ compatibility. */
# ifdef   __cplusplus
}
# endif /*__cplusplus*/
